name: Compile LaTeX CV

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v4

    - name: Install TeX Live
      run: |
        sudo apt-get update
        sudo apt-get install -y texlive-full

    - name: Compile PDF with latexmk
      run: |
        latexmk -pdf -interaction=nonstopmode -output-directory=out main.tex

    - name: Upload PDF
      uses: actions/upload-artifact@v4
      with:
        name: compiled-cv
        path: out/main.pdf
